### ISSUE TITLE
1.9z5 issue 

### ISSUE THREAD

**Issue by SoliduzWoW** [miniZ-miner/miniZ#11]
Having below issues with 1.9z5 linux. 1.9z4 linux works fine.
![image](https://user-images.githubusercontent.com/84977158/199334346-f0bc357c-0d24-45b4-9799-6e1f3af16152.png)

**Comment by i8088** [comment]
Same with me ..      
RTX 3070  I get Error   Cannot find kernel in device code

**Comment by miniZ-miner** [comment]
Hi SoliduzWoW, i8088,
Is it all working well again with v1.9z5b?
Cheers

**Comment by SoliduzWoW** [comment]
Yes update fixed it. Thank you!
