### ISSUE TITLE
KLS support?

### ISSUE THREAD

**Issue by PSLLSP** [miniZ-miner/miniZ#33]
`miniZ` supports KASPA (KAS). There is a clone of KAS, [Karlsen](https://www.karlsencoin.com/) (KLS), it is not perfect clone and mining algorithm is modified, to be ASIC resistant; at least KASPA ASIC miners cannot be used to mine KLS. Could be KLS support added to `miniZ`? That will be cool because only few miners supports KLS right now...

**Comment by miniZ-miner** [comment]
Hi PSLLSP,
Done! 
We'll close this one :)
Cheers
