### ISSUE TITLE
Config File with OC, Fan & PL

### ISSUE THREAD

**Issue by pika28** [miniZ-miner/miniZ#6]
Hello, I just migrated my rigs under Windows on Flux with miniZ.  I set up the conf file and telemetry.  

However, I am unable to include the arguments either in the bat file or the conf file : 

--fanspeed=[fanspeed(%)]
--gpuclock=[gpuclock(MHz)]
--memclock=[memclock(MHz)]
--power=[power(W)]
-pl [power(W)]

Thank you for your help.

**Comment by pika28** [comment]
Hi. The console sends me an error concerning the setting of the fans. The driver version is not compatible. Perhaps it would be wise in the error message to indicate which version is compatible... ;-)

**Comment by miniZ-miner** [comment]
Hi pika28, this should be working well with latest version.
In any case we recommend updating nvidia driver to latest release.
We'll close this issue now.
Thanks for the feedback.
Cheers
