### ISSUE TITLE
[improvement] Dual mining FLUX / Zilliqa 

### ISSUE THREAD

**Issue by thaneb** [miniZ-miner/miniZ#7]
Could we have any hope to get a dual mining option for Flux and Zilliqa ?
Would be perfect for this hard profitability time !

**Comment by miniZ-miner** [comment]
Hi thaneb,
Sorry for a late reply. 
We'll have a close look at this, and will let you know.
Thank you for your suggestion.
Cheers

**Comment by thaneb** [comment]
Great, thank you.
If it's possible to add such option, we may also need to have a "auxiliary algo overclock", because, my memory and understanding of mining Zilliqa are good, it was requiring sames OC than eth algo on gpus in order to be efficient... and eth and flux really doesn't require same kind of OC... (good if you can clear this point while adding the option)

**Comment by KaundaBits** [comment]
dual Flux / Zil is something i would love to be able to do too.

**Comment by miniZ-miner** [comment]
Hi, check latest miniZ v2.0c3 :)
We'll close this one. Let us know how it goes.
Cheers
